name: deploy website
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Node Module
        run: npm install
      - name: Build project
        run: npm run build
      - name: Chnage Directory
        run: cd  build/client/
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-args: "--prod"
          vercel-project-id: ${{
            secrets.PROJECT_ID}} #Required
          working-directory: ./
